language: julia
julia:
  - 1.0.3
os:
  - linux
notifications:
  email: false
codecov: true
after_success:
- julia -e 'cd(Pkg.dir("MyPkg")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'  
